#!/usr/bin/env bash

#
#   This script can be either sourced or executed by bash.
#   Sourcing of this script does not change current environments
#

if [ -z "$BASH_VERSION" ]; then
    echo "Error: should be executed by bash" >&2
    return 2 || exit 2
fi


main() {
    local -
    local prefix='' fd='1'
    if isTruth "${DRY_RUN:-false}"; then
        prefix='echo'
        fd='2'
    fi

    declare -r SCRIPT_DIR=$(dirname "$( realpath "${BASH_SOURCE[0]}" )")

    set -o xtrace
    $prefix 1>&$fd      `# In case of dry run print command to stderr` \
        env --chdir="$SCRIPT_DIR/src" \
            ANSIBLE_CONFIG="$SCRIPT_DIR/src/ansible.cfg" \
            ansible-playbook "${@}"
}


isTruth() (
    shopt -s nocasematch

    if [[ "${1:-false}" =~ ^[[:space:]]*(false|no|0|)[[:space:]]*$ ]]; then
        return 66
    fi
    return 0
)


## Script body

_exitCmd='exit'
if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
    _exitCmd='return'
fi

main "$@"
eval 'unset -f main isTruth;' \
     'unset _exitCmd;' \
     "$_exitCmd $?"
