---
- name: Provision local machine
  hosts: self
  become: yes

  vars:
    install_lastpass_gui: false
    install_vscode: true
    install_chrome: yes
    me: "{{ lookup('env', 'USER') }}"
    my_home: "{{ lookup('env', 'HOME') }}"

  roles:
    - role: env
      tags: [env, all]

    - role: node
      nvm_user: "{{ me }}"
      nvm_version: "v0.33.11"
      nvm_node_version: "11.3.0"   # or "node" for the latest
      nvm_npm_pkgs:
        - pkg: yarn
          version: "*"
      tags: [node, all]

    - role: devpc
      tags: [all]



...
