---
# Environment - current user

- copy:
    src: environment/home/.pam_environment
    dest: "{{ my_home }}/.pam_environment"
    owner: "{{ me }}"
    group: "{{ me }}"
    mode: 0600



- copy:
    src: environment/home/.config/environment.d
    dest: "{{ my_home }}/.config/"
    owner: "{{ me }}"
    group: "{{ me }}"
    mode: 0700
