#!/usr/bin/env bash

#
# $XDG_CONFIG_HOME/bash/bashrc: USER's bashrc. Executed by bash(1) for non-login interactive shells.
#
# Executes instead of hardcoded ~/.bashrc which is removed
#

# /etc/profile -> /etc/bash.bashrc
# /etc/profile -> /etc/profile.d/bash_in_xdg_config_home.sh
# /etc/profile.d/bash_in_xdg_config_home.sh -> ${XDG_CONFIG_HOME}/bash/bash_profile
# ${XDG_CONFIG_HOME}/bash/bash_profile -> ${XDG_CONFIG_HOME}/bash/bashrc

TRACE_SCRIPT=${TRACE_SCRIPT:+"${TRACE_SCRIPT}:"}${BASH_SOURCE}
[[ -z $- ]] && return

CONFIG_DIR=${XDG_CONFIG_HOME:-"${HOME}/.config"}/bash


# See bash(1) for more options
HISTIGNORE='ls:la:ll:l:l.:bg:fg:history:git status'     # skip recording some commands for the sake of readability


# load functions only if they were not loaded by .bash_profile
if ! type sourceDirectory &> /dev/null; then
    [[ -f ${CONFIG_DIR}/bash_functions.sh  ]] && . ${CONFIG_DIR}/bash_functions.sh
fi

# set advanced color prompt instead of the basic one set by /etc/bash.bashrc
[[ -f ${CONFIG_DIR}/bash_prompt.sh ]] && . ${CONFIG_DIR}/bash_prompt.sh

# load user's aliases
[[ -f ${CONFIG_DIR}/bash_aliases.sh ]] && . ${CONFIG_DIR}/bash_aliases.sh

# load completions
sourceDirectory --files="*.*sh" ${CONFIG_DIR}/completion.d


# make less more friendly for non-text input files, see lesspipe(1)
[[ -x /usr/bin/lesspipe ]] && eval "$(SHELL=/bin/sh lesspipe)"

# set vim as man pager
if which vim >/dev/null; then
    export MANPAGER="/bin/sh -c \"col -b | vim -c 'set ft=man ts=8 nomod nolist nonu noma' -\""
fi


# disable C-q & C-s bullshit
[[ $- == *i* ]] && stty -ixon


# tmux
if which tmux >/dev/null
then
     echo 'ignore tmux yet' > /dev/null	
#    ! tmux has-session -t main 2>/dev/null  &&  tmux new-session -d -s main
#    shopt -q login_shell  && tmux new-session -t  
#    then
#        tmux new-session -d -s dev
#    else
#        declare -i tmuxSessions=$(tmux list-sessions 2> /dev/null| cut --delimiter=: --fields=1| sort --numeric-sort| tail --lines=1)
#        [[ tmuxSessions != "dev" ]]
#	let tmuxSessions++
#        tmux new-session -t dev -s $tmuxSessions
#        unset tmuxSessions
#    fi
fi


#keychain id_rsa
#. ~/.keychain/`uname -n`-sh

unset CONFIG_DIR
