---

- name: Install common packages
  apt:
    update_cache: yes
    name:
      - git
      - httpie
      - mc
      - neovim
      - stow
      - tmux
      - tmuxinator
      - tree
      - xclip
      - zeal
    state: present

...
