---

# in Ubuntu 18.10 can be installed as usual package

- apt:
    name: lastpass-cli
    state: present

# - name: check if lastpass-cli installed
#   shell: command -v lpass --version >/dev/null 2>&1; 
#   register: lastpass_exists
#   ignore_errors: yes
#   changed_when: lastpass_exists.rc != 0

# - name: install lastpass-cli dependencies
#   apt:
#     name:
#       - bash-completion
#       - build-essential
#       - cmake
#       - libcurl4
#       - libcurl4-openssl-dev
#       - libssl-dev
#       - libxml2
#       - libxml2-dev
#       - libssl1.1
#       - pkg-config
#       - ca-certificates
#       - asciidoc 
#       - xsltproc
#   when: lastpass_exists.changed  

# - shell: curl --location --remote-name https://github.com/lastpass/lastpass-cli/releases/download/v1.3.1/lastpass-cli-1.3.1.tar.gz
#   args:
#     chdir: "{{ my_home }}/Downloads"
#     creates: "{{ my_home }}/Downloads/lastpass-cli-1.3.1.tar.gz"
#   when: lastpass_exists.changed

# - shell: tar xzf lastpass-cli-1.3.1.tar.gz
#   args:
#     chdir: "{{ my_home }}/Downloads"
#     creates: "{{ my_home }}/Downloads/lastpass-cli-1.3.1"
#   when: lastpass_exists.changed  

# - shell: "make; make install PREFIX=/usr/local"
#   args:
#     chdir: "{{ my_home }}/Downloads/lastpass-cli-1.3.1"
#   when: lastpass_exists.changed

# make install-doc

# - file:
#     path: "{{ my_home }}/Downloads/lastpass-cli-1.3.1"
#     state: absent
...