---
# tasks file for devpc

- name: Create users
  include_tasks: users.yaml


- name: Install packages
  apt:
    update_cache: yes
    name:
      - git
      - mc
      - neovim
      - stow
      - xclip
      - zeal
    state: present


- name: Install SSH server
  include_tasks: ssh_server.yaml


- name: Install git-crypt
  include_tasks: git-crypt.yaml  


- name: Install VS Code
  include_tasks: vscode.yaml    


- name: Install Vagrant and companions
  include_tasks: vagrant.yaml


- name: Install dotfiles
  include_tasks: dotfiles.yaml


#
# @TODO: Install Lastpass
#

- name: Install Lastpass
  include_tasks: lastpass.yaml
  when: false

#
# @TODO: Install lastpass-cli
#