---
# Ensure important local accounts exist and are in shape

- name: Create users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    home: "/home/{{ item.name }}"
    shell: /bin/bash
    groups: "{{ item.groups }}"
    append: yes
  with_items:
    - { name: ansible, groups: [sudo, adm], password: '$6$mysecretsalt$ojXsuJlI3sHW156nZeWMMESAdKY42tLJN4nLZYenmyiHPsVVkeNGj3ZBprtlBFbpI2FwpRtp4qJP3G9iL8im71' }
    - { name: astaroth, groups: [sudo, adm], password: '$6$abrakadabra$ux.sOuxjqC3cNggugn8NaYbVqC2Xkqz0/E4E7/MYsr3CELfM0ErO5bYeD3gj3yB8S/axW6jYBBQe6i.y3Pcgv.' }
    - { name: mao, groups: [sudo, adm, ansible], password: '$6$abrakadabra$OXB4pmH2Rk.xW048zDADpCrG0ZkWHAAg6bPkCtQ/Owgm0wbMRwXDn3YWUV4BA3Nai8rizljhs2SaoOTr8sqVL/' }

- name: Add public SSH keys
  copy:
    src: .ssh
    dest: "/home/{{ item }}"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: u+rwx,g-rwx,o-rwx
  with_items:
    - mao
    - ansible
    - astaroth

- name: Ensure correct permissions for .ssh directory and files
  file:
    path: "{{ item.path }}"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "{{ item.mode }}"
  with_items:
    - { name: mao, path: /home/mao/.ssh, mode: '0700' }
    - { name: mao, path: /home/mao/.ssh/authorized_keys, mode: '0644' }
    # - { name: mao, path: /home/mao/.ssh/bb88_ed25519, mode: '0600' }
    # - { name: mao, path: /home/mao/.ssh/bb88_ed25519.ppk, mode: '0600' }
    # - { name: mao, path: /home/mao/.ssh/bb88_ecdsa, mode: '0600' }
    # - { name: mao, path: /home/mao/.ssh/bb88_ecdsa.ppk, mode: '0600' }
    # - { name: mao, path: /home/mao/.ssh/bb88_rsa_2048, mode: '0600' } 
    # - { name: mao, path: /home/mao/.ssh/bb88_rsa_2048.ppk, mode: '0600' }
    # - { name: mao, path: /home/mao/.ssh/bb88_rsa_4096, mode: '0600' }
    # - { name: mao, path: /home/mao/.ssh/bb88_rsa_4096.ppk, mode: '0600' }
    - { name: ansible, path: /home/ansible/.ssh, mode: '0700' }
    - { name: ansible, path: /home/ansible/.ssh/authorized_keys, mode: '0644' }
    - { name: astaroth, path: /home/astaroth/.ssh, mode: '0700' }
    - { name: astaroth, path: /home/astaroth/.ssh/authorized_keys, mode: '0644' }


- stat:
    path: "/home/{{ me }}/.ssh/config"
  register: ssh_config

- name: ssh config to access Github
  copy: 
    src: .ssh/config
    dest: "/home/{{ me }}/.ssh/"
  when: ssh_config.stat.path is not defined


- name: Copy a new "sudoers" file into place, after passing validation with visudo
  copy:
    src: etc/sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0400
    validate: /usr/sbin/visudo -cf %s