---

- name: Get user's home dir
  shell: >
      getent passwd {{ nvm_user }} | cut -d: -f6
  changed_when: false
  register: nvm_user_home

- set_fact:
    nvm_dir: "{{ nvm_user_home }}/.nvm"

- name: Check if nvm is installed
  shell: tarsnap --version | grep {{ tarsnap_version }} --color=never
  register: tarnsap_installed
  changed_when: "tarnsap_installed.stderr != ''"
  ignore_errors: yes

- stat:
    path: "{{ nvm_dir}}/nvm.sh"
  register: nvm

- name: Execute nvm installation script
  shell: >
      curl -o- https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/install.sh | bash
  when: nvm.stat.exists == false
  args:
    warn: false
