---

- name: Get user's home dir
  shell: >
      getent passwd {{ nvm_user }} | cut -d: -f6
  changed_when: false
  register: nvm_user_home

- name: Set nvm base directory
  raw: |
    if [[ -v NVM_DIR ]]; then
        echo $NVM_DIR
    elif [[ -v XDG_CONFIG_HOME ]]; then
        echo $XDG_CONFIG_HOME/nvm
    else
        echo $HOME/.nvm
    fi
  args:
    executable: /bin/bash
  become_user: "{{ nvm_user }}"
  register: nvm_dir_raw
  changed_when: false

- set_fact:
    nvm_dir: "{{ nvm_dir_raw.stdout | trim }}"

- name: Execute nvm installation script
  shell: >
      curl -o- https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/install.sh | bash
  args:
    creates: "{{ nvm_dir }}/nvm.sh"
    warn: false
  become_user: "{{ nvm_user }}"
