---

- name: NVM | nvm | get stats on nvm
  stat: path="{{ nvm_dest }}"
  register: nvm_stat

- name:  NVM | nvm | create .nvm directory
  file:
    path: "{{ nvm_dest }}"
    group: "{{ nvm_user }}"
    owner: "{{ nvm_user }}"
    mode: 0755
    recurse: yes
    state: directory
  when: not nvm_stat.stat.exists

- name: NVM | nvm | download nvm script
  get_url:
    dest: "{{ nvm_dest }}"
    url: https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/nvm.sh

- include: permission.yml

- name: NVM | nvm | ensure ~/.bashrc exists
  copy: 
    content: "" 
    dest: "{{ nvm_working_path }}/.bashrc" 
    force: no

- name: NVM | nvm | add nvm to ~/.bashrc
  lineinfile: dest="{{ nvm_working_path }}/.bashrc" line="source ~/.nvm/nvm.sh"
