---
- name: Provision local machine
  hosts: self
  become: yes
  remote_user: ansible

  vars_files:
    - vars/servers.yml
    - vars/configs.yml

  vars:
    install_vscode: true
    install_chrome: yes
    me: "{{ lookup('env', 'USER') }}"
    my_home: "{{ lookup('env', 'HOME') }}"

  roles:
    - role: common
      vars:
        commonRole_parameter_001: text from playbook

    - role: ntg7
      vars:
        cc: clang
        shell: zsh

    - role: git_cache_host
      vars:
        cc: gcc
        shell: bash
...
