---
- name: Provision local machine
  hosts: self
  become: yes

  vars_files:
    - vars/servers.yml
    - vars/configs.yml

  vars:
    install_lastpass_gui: false
    install_vscode: true
    install_chrome: yes
    me: "{{ lookup('env', 'USER') }}"
    my_home: "{{ lookup('env', 'HOME') }}"

  roles:
    - role: env
      tags: [env, profile, all]

    - role: common
      vars:
        commonRole_parameter_001: text from playbook

    - role: node
      nvm_user: "{{ me }}"
      nvm_version: "v0.33.11"
      nvm_node_version: "node"   # or "node" for the latest
      nvm_npm_pkgs:
        - pkg: yarn
          version: "*"
      tags: [node, all]

    - role: devpc
      tags: [devpc, all]

    - role: ntg7
      vars:
        cc: clang
        shell: zsh

    - role: git_cache_host
      vars:
        cc: gcc
        shell: bash
...
