---
all:
  hosts:
    localhost:
  children:
    work:
      hosts:
        localhost.localdomain:
        aamelnyk-tmp-lws:
    home:
      hosts:
        dell-5591:
    self:
      hosts:
        localhost:
