---
# tasks file for env

- name: Environment - all users
  import_tasks: 100-env-all.yaml
  tags:
    - env.all

- name: Environment - root
  import_tasks: 100-env-root.yaml
  tags:
    - env.root

- name: Environment - user
  import_tasks: 100-env-user.yaml
  tags:
    - env.user



- name: Profile - all users
  import_tasks: 200-profile-all.yaml
  tags:
    - profile.all

- name: Profile - root
  import_tasks: 200-profile-root.yaml
  tags:
    - profile.root

# - name: Profile - user
#   include_tasks: 200-profile-user.yaml
